const products=[
{name:'Gulab Jamun',tamil:'குலாப் ஜாமுன்',cat:'sweets',price:90,unit:'250g',desc:'Soft khoya dumplings soaked in cardamom-rose syrup',art:'GJ',tag:'Popular'},
{name:'Motichoor Laddu',tamil:'மோதிசூர் லட்டு',cat:'sweets',price:95,unit:'250g',desc:'Fine boondi pearls bound with ghee and saffron',art:'ML',tag:'Popular'},
{name:'Rasgulla',tamil:'ரஸ்குல்லா',cat:'sweets',price:85,unit:'250g',desc:'Spongy chenna balls in light sugar syrup',art:'RG'},
{name:'Mysore Pak',tamil:'மைசூர் பாகு',cat:'sweets',price:110,unit:'250g',desc:'Ghee-rich gram flour fudge, melts in the mouth',art:'MP'},
{name:'Pistachio Barfi',tamil:'பிஸ்தா பர்பி',cat:'sweets',price:140,unit:'250g',desc:'Silver-leafed pista barfi, cut in diamonds',art:'PB'},
{name:'Rasmalai',tamil:'ரஸ்மலை',cat:'sweets',price:105,unit:'250g',desc:'Chenna discs in saffron milk, chilled',art:'RM'},
{name:'Dark Truffle Cake',tamil:'டார்க் ட்ரஃபிள் கேக்',cat:'cakes',price:450,unit:'500g',desc:'Half-kg dark chocolate truffle, 100% eggless options',art:'DT',tag:'Popular'},
{name:'Butterscotch Cake',tamil:'பட்டர்ஸ்காட்ச் கேக்',cat:'cakes',price:420,unit:'500g',desc:'Caramel crunch, whipped cream, butterscotch glaze',art:'BC'},
{name:'Red Velvet Cake',tamil:'ரெட் வெல்வெட் கேக்',cat:'cakes',price:480,unit:'500g',desc:'Beetroot-red sponge with cream cheese frosting',art:'RV'},
{name:'Plum Cake',tamil:'பிளம் கேக்',cat:'cakes',price:120,unit:'250g',desc:'Fruit & nut plum cake, baked fresh daily',art:'PC'},
{name:'Vanilla Cupcakes',tamil:'வெண்ணிலா கப்கேக்',cat:'cakes',price:180,unit:'Box of 6',desc:'Box of 6 soft vanilla cupcakes with buttercream',art:'VC'},
{name:'Egg Puff',tamil:'எக் பஃப்',cat:'savouries',price:20,unit:'1 piece',desc:'Flaky Kerala-style puff with spiced egg filling',art:'EP'},
{name:'Veg Puff',tamil:'வெஜ் பஃப்',cat:'savouries',price:15,unit:'1 piece',desc:'Crisp pastry with mixed-veg masala filling',art:'VP'},
{name:'Chicken Puff',tamil:'சிக்கன் பஃப்',cat:'savouries',price:30,unit:'1 piece',desc:'Golden puff with peppery chicken filling',art:'CP'},
{name:'Dilkhush',tamil:'தில்குஷ்',cat:'savouries',price:25,unit:'1 piece',desc:'Sweet-coconut stuffed bun, square cut',art:'DK'},
{name:'Honey Cake',tamil:'ஹனி கேக்',cat:'savouries',price:30,unit:'1 piece',desc:'Iyengar-style syrup-soaked honey cake slice',art:'HC'},
{name:'Festival Sweet Box',tamil:'பண்டிகை இனிப்பு பெட்டி',cat:'combos',price:420,unit:'Gift Box',desc:'Assorted 500g sweets + 250g savouries in gift box',art:'FS',tag:'Popular'},
{name:'Birthday Party Pack',tamil:'பிறந்தநாள் பார்ட்டி பேக்',cat:'combos',price:650,unit:'Party Pack',desc:'Half-kg cake + 6 cupcakes + 250g savouries',art:'BP'}];
const productImages=["assets/gulab-real.jpg", "assets/sweets-real.jpg", "assets/gulab-real.jpg", "assets/sweets-real.jpg", "assets/sweets-real.jpg", "assets/gulab-real.jpg", "assets/cakes-real.webp", "assets/chocolate-real.jpg", "assets/cakes-real.webp", "assets/chocolate-real.jpg", "assets/cakes-real.webp", "assets/savoury-real.jpg", "assets/savoury-real.jpg", "assets/savoury-real.jpg", "assets/savoury-real.jpg", "assets/savoury-real.jpg", "assets/sweets-real.jpg", "assets/cakes-real.webp"];
let basket=JSON.parse(localStorage.getItem('mummy-basket')||'[]');let currentFilter='all';
const grid=document.querySelector('#product-grid');
function renderProducts(){grid.innerHTML=products.filter(p=>currentFilter==='all'||p.cat===currentFilter).map((p,i)=>`<article class="product-card"><div class="product-photo-wrap"><img class="product-photo" src="${productImages[products.indexOf(p)]}" alt="${p.name}" loading="lazy"><span class="product-photo-label">${p.art}</span></div>${p.tag?`<span class="product-tag">${p.tag}</span>`:''}<h3>${p.name}</h3><p class="product-tamil">${p.tamil}</p><p class="product-desc">${p.desc}</p><div class="product-bottom"><span class="price">₹${p.price} <small>/ ${p.unit}</small></span><button class="add-btn" data-add="${products.indexOf(p)}">Add to order <span>+</span></button></div></article>`).join('');}
function updateBasket(){localStorage.setItem('mummy-basket',JSON.stringify(basket));const count=basket.reduce((s,i)=>s+i.qty,0);document.querySelector('#basket-count').textContent=count;document.querySelector('#fab-count').textContent=count;const wrap=document.querySelector('#basket-items');if(!basket.length){wrap.innerHTML='<p class="empty-state">Your order is empty.<br /><span>Add a few sweets, cakes or savouries to get started.</span></p>';}else{wrap.innerHTML=basket.map(item=>`<div class="basket-item"><div class="product-art art-${item.product.cat==='cakes'?'cake':item.product.cat==='savouries'?'savoury':item.product.cat==='combos'?'combo':'sweet'}">${item.product.art}</div><div><h4>${item.product.name}</h4><p>₹${item.product.price} · ${item.product.unit}</p><div class="qty-controls"><button data-minus="${item.index}" aria-label="Decrease quantity">−</button><strong>${item.qty}</strong><button data-plus="${item.index}" aria-label="Increase quantity">+</button></div></div><button class="remove" data-remove="${item.index}">Remove</button></div>`).join('');}const wa=document.querySelector('#basket-whatsapp');const lines=basket.map(i=>`• ${i.product.name} × ${i.qty} — ₹${i.product.price*i.qty}`);const name=(document.querySelector('#order-name')?.value||'').trim(),phone=(document.querySelector('#order-phone')?.value||'').trim(),branch=document.querySelector('#order-branch')?.value||'Salai Bazar',note=(document.querySelector('#order-note')?.value||'').trim();const text=`Hello New Mummy Bakery! I'd like to place an order:\n\n${lines.join('\n')}\n\nName: ${name||'To be confirmed'}\nPhone: ${phone||'To be confirmed'}\nPickup branch: ${branch}\n${note?'Note: '+note+'\n\n':''}(From your website)`;wa.href=`https://wa.me/917010363649?text=${encodeURIComponent(text)}`;wa.setAttribute('aria-disabled',basket.length?'false':'true');}
function openBasket(){document.querySelector('.basket').classList.add('open');document.querySelector('.basket').setAttribute('aria-hidden','false');document.querySelector('.basket-overlay').classList.add('open');}
function closeBasket(){document.querySelector('.basket').classList.remove('open');document.querySelector('.basket').setAttribute('aria-hidden','true');document.querySelector('.basket-overlay').classList.remove('open');}
if(grid)grid.addEventListener('click',e=>{const btn=e.target.closest('[data-add]');if(!btn)return;const index=Number(btn.dataset.add),found=basket.find(i=>i.index===index);if(found)found.qty++;else basket.push({index,product:products[index],qty:1});updateBasket();document.querySelector('.basket-fab').classList.add('bump');setTimeout(()=>document.querySelector('.basket-fab').classList.remove('bump'),400);btn.textContent='Added ✓';setTimeout(()=>btn.innerHTML='Add to order <span>+</span>',900);});
const basketItems=document.querySelector('#basket-items');if(basketItems)basketItems.addEventListener('click',e=>{const minus=e.target.closest('[data-minus]'),plus=e.target.closest('[data-plus]'),remove=e.target.closest('[data-remove]');if(minus){const x=basket.find(i=>i.index===Number(minus.dataset.minus));if(x.qty>1)x.qty--;else basket=basket.filter(i=>i!==x)}if(plus){basket.find(i=>i.index===Number(plus.dataset.plus)).qty++}if(remove)basket=basket.filter(i=>i.index!==Number(remove.dataset.remove));updateBasket();});
document.querySelectorAll('.category').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.category').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentFilter=btn.dataset.filter;renderProducts();}));
const fab=document.querySelector('.basket-fab'),close=document.querySelector('.basket-close'),overlay=document.querySelector('.basket-overlay');if(fab)fab.addEventListener('click',openBasket);if(close)close.addEventListener('click',closeBasket);if(overlay)overlay.addEventListener('click',closeBasket);const toggle=document.querySelector('.menu-toggle');if(toggle)toggle.addEventListener('click',e=>{const nav=document.querySelector('.mobile-nav'),open=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!open));nav.hidden=open;});document.querySelectorAll('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.mobile-nav').hidden=true;document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}));
if(grid)renderProducts();if(document.querySelector('#basket-count')){updateBasket();['order-name','order-phone','order-branch','order-note'].forEach(id=>document.querySelector('#'+id)?.addEventListener('input',updateBasket));}

const contactForm=document.querySelector('#contact-form');if(contactForm)contactForm.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(contactForm);const text=`Hello New Mummy Bakery!\n\nName: ${data.get('name')}\nPhone: ${data.get('phone')}\nEnquiry: ${data.get('message')}\n\n(From your website)`;window.open(`https://wa.me/917010363649?text=${encodeURIComponent(text)}`,'_blank','noopener');});

const revealItems=document.querySelectorAll('main > section:not(.menu-page-section), .site-footer');const staggerSelectors='.home-highlights,.reviews-grid,.gallery-grid,.values-grid,.branch-grid-contact,.home-visit-links,.about-mosaic';revealItems.forEach((el,index)=>{el.classList.add('reveal');if(el.matches(staggerSelectors))el.classList.add('reveal-stagger');el.style.setProperty('--reveal-delay',`${Math.min(index*70,280)}ms`);});if('IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target);}}),{threshold:.12,rootMargin:'0px 0px -7% 0px'});revealItems.forEach(el=>revealObserver.observe(el));}else revealItems.forEach(el=>el.classList.add('is-visible'));

const backToTop=document.createElement('button');backToTop.type='button';backToTop.className='back-to-top';backToTop.setAttribute('aria-label','Back to top');backToTop.innerHTML='<span aria-hidden="true">↑</span>';if(document.querySelector('.basket-fab'))backToTop.classList.add('has-basket');document.body.append(backToTop);const updateBackToTop=()=>backToTop.classList.toggle('is-visible',window.scrollY>400);window.addEventListener('scroll',updateBackToTop,{passive:true});backToTop.addEventListener('click',()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));updateBackToTop();
